* Library Information
 Readme.org --- Miscellaneous macros

 - Filename :: [[file:jb-misc-macros.el][jb-misc-macros.el]]
 - Description :: Miscellaneous macros
 - Author :: Joe Bloggs <vapniks@yahoo.com>
 - Maintainer :: Joe Bloggs <vapniks@yahoo.com>
 - Copyleft (Ↄ) 2013, Joe Bloggs, all rites reversed.
 - Created :: 2013-06-05 01:38:24
 - Version :: 0.1
 - Last-Updated :: 2013-06-05 01:38:24
 -           By :: Joe Bloggs
 - URL :: https://github.com/vapniks/jb-misc-macros
 - Keywords :: lisp
 - Compatibility :: GNU Emacs 24.3.1
 - Package-Requires :: ((macro-utils "1.0"))

* Possible Dependencies

macro-utils.el

* Commentary

Bitcoin donations gratefully accepted: 1AoGev8FTwVVspNZxHuu8LMztAwxdzRndZ

This library contains miscellaneous macros that I use in my projects, or that I thought might be useful.

* Functions & Macros:
Below is a list of functions and macros defined in this file:

 - `lastcar' : Return the last element of a list
 - `jb-get-matching-name-buffers' : Return list of buffers with names matching REGEX
 - `jb-get-matching-mode-buffers' : Return list of buffers with mode names matching REGEX
 - `jb-apply-partially' : Return a function that is a partial application of FUN to ARGS
 - `jb-untilnext' : Evaluate INITFORM followed by NEXTFORM repeatedly. Stop when one of them returns non-nil, and returning that value.
 - `jb-list-subset' : Return elements of LIST corresponding to INDICES.
 - `jb-number-list' : Return a sequential list of numbers from START to END.
 - `jb-read-key-menu' : Prompt the user for a key and return the results of evaluating the corresponding form in the list FORMS.
 - `build-symbol-and-value-bindings' : Return a list of ‘let’ binding pairs from ARG-SPECS, which binds variables to symbols & values of args.
 - `with-symbol-and-value-bindings' : Create symbol and value bindings according to ARG-SPECS, then evaluate BODY.
 - `set-symbol-and-value-bindings' : Use ‘setq’ to set symbol and value variables according to ARG-SPECS.

* Examples
Prompt the user for a free keybinding:
#+BEGIN_SRC emacs-lisp
 (untilnext (read-key-sequence "Enter a key: ")
            (read-key-sequence "That key is already bound to a command. Try again: ")
            (lambda (x) (not (key-binding x))))
#+END_SRC
 Keep a track of the number of prompts
#+BEGIN_SRC emacs-lisp
 (untilnext (read-number "What is 1+1? Attempt 1: ")
            (prog1 (read-number  (concat "Wrong! Try again. Attempt " (number-to-string num) ": "))
              (setq num (1+ num)))
            (lambda (x) (= x 2))
            (num 1))
#+END_SRC

#+BEGIN_SRC emacs-lisp
 `(let ,(build-symbol-and-value-bindings '((foo fsym fval) ('bar nil bval) (1 2 3)))
   fsym)
#+END_SRC
expands to:
(let ((fsym 'foo)
      (fval (if (boundp 'foo) foo nil))
      (argsym2 'bar)
      (argval2 (if (boundp 'bar) bar nil))
      (argsym3 nil)
      (argval3 '(1 2 3)))
  fsym)"


* Installation

 - Download the library, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'jb-misc-macros) in your ~/.emacs file
